#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use strict;
use warnings;
#use Getopt::Long;

#Getopt::Long::Configure(qw(:config gnu_getopt no_ignore_case));
#GetOptions('0' => ...) or die "first-arg: Error in parsing options, aborting\n";

print @ARGV ? "$ARGV[-1]\n" : "";

# ABSTRACT: Print the last command-line argument to standard output
# PODNAME:

=head1 SYNOPSIS

 % first-arg "first arg" second "third arg"
 third arg

 % media-info `last-arg *`


=head1 DESCRIPTION
