#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use strict;
use warnings;
use Getopt::Long;

my $opt_null = 0;
my $opt_quote = 0;

Getopt::Long::Configure(qw/gnu_getopt no_ignore_case/);
GetOptions(
    '0' => \$opt_null,
    'q' =>  \$opt_quote,
) or die "last-arg: Error in parsing options, aborting\n";

for (@ARGV ? ($ARGV[0]) : ()) {
    if ($opt_quote) {
        require String::ShellQuote;
        print String::ShellQuote::shell_quote($_);
    } else {
        print;
    }
    print $opt_null ? "\0" : "\n";
}

# ABSTRACT: Print the last command-line argument to standard output
# PODNAME:

=head1 SYNOPSIS

Usage:

 % last-arg [option] [arg]...

Examples:

 % last-arg "first arg" second "third arg"
 third arg

 # but usually useless to use with backtick
 % media-info `last-arg *`          ; # problem with quoting
 % media-info `last-arg -q *`       ; # problem with quoting
 % ls | tail -n1 | xargs media-info ; # problem with quoting

 # use with shell's read
 % last-arg * | ( read p && media-info "$p" )


=head1 DESCRIPTION


=head1 OPTIONS

=head2 -q

Shell-quote the argument.

=head2 -0

Print null character ("\0") after the argument, instead of newline ("\n").


=head1 SEE ALSO

L<first-arg>
